### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by kyr0** [mtytel/vital#10]
Would be cool to make it compile on macOS -- I'll take a look but can't guarantee much

**Comment by mtytel** [comment]
There are xcode projects in plugin/builds/osx and standalone/builds/osx

**Comment by kyr0** [comment]
Yes, but they are configured in a way that you cannot build them easily; they belong to "Mac Developer" in a certain team and the firebase.framework + firebase_auth.framework is missing for the builds. I was about to automate that process so you could just `make` the AU, VST etc. -- the only thing that needs to be changed in upstream is that the team association must be removed for everybody else to build it without issues. Is this worth a PR from me - would you accept it?

**Comment by magnetophon** [comment]
@kyr0 PR's won't be accepted for this repo in general.

**Comment by Jobsecond** [comment]
Don't run `make` to build on macOS, because the `Makefile` of this project is intended for Linux. Instead, use the Xcode project `.xcodeproj` to build on macOS:
* `standalone/builds/osx` for Standalone app
* `plugin/builds/osx` for Plugin

If Xcode shows **"No account for team"** error, you need to change the `Development team` of each Target to your own developer account.
