### ISSUE TITLE
License with additional terms?

### ISSUE THREAD

**Issue by rdrpenguin04** [mtytel/vital#11]
The README currently notes additional restrictions on top of the GPL3 license being used. However, the GPL3 license specifically states:

> If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.

As such, any additional conditions being added are null and void. You should consider if you want to change your license or if you are okay with dropping your additional terms.

As a side note, because of this clause, distributing on iOS may in fact be possible without violating the license on your software. For further information, I refer you to [an article on Stack Exchange](https://opensource.stackexchange.com/questions/9500/is-apple-allowed-to-distribute-gplv3-licensed-software-through-its-ios-app-store) discussing the problem.

**Comment by taylordotfish** [comment]
I don't think there are any additional terms that contradict the GPL. Although I'm not a legal expert, I'll go through my understanding of each item in the “Things you can't do with this source” section:

* > Do not create an app and distribute it on the iOS app store. The app store is not comptabile with GPLv3…

  This isn't an additional term; it's an explanation of what the GPL already disallows. Although this hasn't been tested in court as far as I know, it is commonly thought that distributing a GPLv3-covered program on the iOS app store is a license violation unless you're the copyright holder or have permission from the copyright holders to do so. [This is the FSF's explanation](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement)—they discuss GPLv2 but say in that same article that their analysis applies to all versions of the GPL.

* > Do not use the name "Vital", "Vital Audio", "Tytel" or "Matt Tytel" for marketing…

  Adding this term is allowed by the GPL. See subsections c), d), and e) of section 7:

  ```
  Notwithstanding any other provision of this License, for material you
  add to a covered work, you may (if authorized by the copyright holders of
  that material) supplement the terms of this License with terms:

      ...

      c) Prohibiting misrepresentation of the origin of that material, or
      requiring that modified versions of such material be marked in
      reasonable ways as different from the original version; or

      d) Limiting the use for publicity purposes of names of licensors or
      authors of the material; or

      e) Declining to grant rights under trademark law for use of some
      trade names, trademarks, or service marks; or
  ```

* > Do not connect to any web service at https://vital.audio, https://account.vital.audio or https://store.vital.audio from your own builds. This is against the terms of using those sites.

  This isn't a matter of the GPL, but rather, as the item states, a matter of the those sites' terms of use. Connecting to those sites in a modified version of Vital wouldn't be a GPL violation; it would be a violation of the terms of use of those services and could fall under laws prohibiting the unauthorized use of digital services. It would also be a violation of those sites' terms of use to use them in a program that contained no code from this repository—this issue is independent of the GPL.

**Comment by mtytel** [comment]
I think @taylordotfish puts this pretty well. 

The second two points are not about the source or binaries and are separate from what the GPL covers in this case. I can keep my own trademarks and have terms for web services.

As for the first point, it is a clarification of what the GPLv3 allows and not an additional term similar to the GPL FAQ https://www.gnu.org/licenses/gpl-faq.html

I'd appreciate it if you didn't make assertions about legality on this unless you're a lawyer or you've consulted one. 
To answer your point though, first you would have to create a build using GPLv3 compatible libraries. Seeing that almost all iOS Frameworks are closed source I think this would be a technological feat. After you have this build if you tried to distribute it on the iOS app store and you're correct, it nullifies all terms that Apple itself specifies. This is most certainly against Apple's terms and so would get removed by them.

I'm not going to spend any more time arguing legality here. If you still disagree you can have a lawyer reach out to me at licensing@vital.audio
