### ISSUE TITLE
Vitalium for Debian

### ISSUE THREAD

**Issue by tank-trax** [mtytel/vital#14]
I posted [this](https://github.com/tank-trax/vitalium/releases/tag/theta) Standalone and VST3 build

I did my best to remove the instances of Vial and Vital and rendered it to Vitalium
Turned of the Authorization, no VST2 or LV2

If anyone wants to look at the vitalium-1.0.6 branch is where the changes I made are.

I am not a developer. Merely a Linux audio user that knows how to compile software and tweak code a bit (blunt hacking is more like it)

If there are changes that need to be made to comply with your wishes Matt please let me know and if you want me to take the builds down will do so in a jiffy.

Thanks

**Comment by falkTX** [comment]
There is a lot more stuff involved than just that.
I am porting over vital to [distrho-ports](https://github.com/DISTRHO/DISTRHO-Ports) and it is already working well. I am focusing on the lv2 version, a couple of fixes were needed in the wrapper in order to make it play nice (juce has changed quite a bit since I did that part)
I am also changing default colors so that it is more recognizable from first glance that this is not the official version.
![Screenshot_20210302_001511](https://user-images.githubusercontent.com/1334853/109576848-6fb5fb80-7aec-11eb-8009-0f6447ed30d4.png)

**Comment by tank-trax** [comment]
Looks great. Had I known I'd have forked your branch instead. :-) I am also more interested in the VST3 than the LV2.

**Comment by tank-trax** [comment]
Looks great. Had I known I'd have forked your branch instead. :-) I do prefer the VST3 to the LV2.

**Comment by falkTX** [comment]
> Just tested the VST3 from your ports and it's can't load in Bitwig. Black screen. Crashed and froze the app.

can you try the VST2 version? VST3 handling on linux is unusual with the way it uses idle threads.

**Comment by tank-trax** [comment]
![image](https://user-images.githubusercontent.com/41337033/109700097-5dc17080-7b5f-11eb-904c-8110b38d9834.png)

**Comment by tank-trax** [comment]
the VST3 I built is very stable (in fact it plays and responds exactly as I had hoped and asked that it would as my hunch before it was open sourced is the Auth and TTW were problematic

will continue to use my personal build, I presented my frustrations and opinions on this matter at the closed distrho-ports issue

**Comment by tank-trax** [comment]
as an FYI I have incorporated some of falk's fixes and the taylor.fish LV2 JUCE wrapper changes to build [successfully](https://github.com/tank-trax/vital/tree/vitality+minus-1.0.6) LV2, VST3 and Standalone
