### ISSUE TITLE
License for presets

### ISSUE THREAD

**Issue by falkTX** [mtytel/vital#15]
I have a question regarding the license of presets shipped with Vital.
Can those be redistributed? If so, under what terms?

Currently any vital fork builds do not have any presets.
Would be nice to have at least a few of them, best if it would match the official "free" pack.

**Comment by mtytel** [comment]
No they can't be redistributed. Since content is pretty much my core business model I made it so I'm the only distributor. I also apply this to the free presets to keep people in the Vital system so they can easily upgrade to Plus/Pro or subscribe if they decide to.

You're welcome to scan user's vital configs and get where they are installed though if the user has Vital on their computer.

**Comment by falkTX** [comment]
Understood, thanks for the clear answer.

I will try to get some user contributed presets and ship with those by default.

**Comment by plainoldcheese** [comment]
Hi, would the same restrictions apply to any presets made using the factory wavetables?
I am building a bank of presets that I would like to distribute for free that use the free factory wavetables but I am unsure whether I will be allowed to distribute them.

sorry for commenting on a closed issue but I didn't think it necessary to open a new one and fragment the information.

**Comment by magnetophon** [comment]
@plainoldcheese:I think Matt's answer is pretty clear on that:

> Since content is pretty much my core business model I made it so I'm the only distributor.

So no, (patches using) factory wavetables are not distributable either.

**Comment by plainoldcheese** [comment]
ok thank you
